@startuml

class FoodVendor{
  #id
  +__construct()
}


class Supplier extends FoodVendor {
  - name
  - contact
  - address
  - pricing
  +__construct()
}


class Ingredient extends FoodVendor {
  - name
  - type
  - supplierId
  +__construct()
}

' Dish class inherits from Entity
class Dish extends FoodVendor {
  - name
  - price
  - ingredientId
  +__construct()
}

@enduml
